# Generated by Django 2.1.3 on 2018-12-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPost',
        ),
    ]
